language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- no_open_mp ;
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- travis_wait 100 R CMD INSTALL --build ${PKG_TARBALL}
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: EKk2YJS+pxr/CDqLUtdbzqpkrvtw5P2SuRXTxAhwZRqtghQvffutKTuepDiIN8BVIN8Z38/rr1XhADjB1/MiEghuexWWlg/YdPDEIp6AHGu4iccAoeaf1e+GlA/nuTcagf4Z0518zmozUV09qqSCb0FP2fWCljQJa5BcMrN2FZdha0Kx0cqOVxkeTdjv5XQuME3jH8CgqqQKKeQc8QP6rQxkOarufxul97pODInstH2OM5sKZzK3oZDADqS33rB7Md0zCpiLjH9opFYlZ5RfMavzI7AHlBPEFs3PSWbHrDnZ8jjlLdGsdFdajrESwRpdUKmbzCt8mZxhUBJfN0xKXF7z02bEE2aywaMJ8yZUOxIoMmQo716UVBdp7Sn5KHZp9i2UlJM3j9a4ITNSrICa64FJn+I/oMg1vJcJcMaWTupR24Qb5il24qpaYrMQgfpa4kfvPYNWIY0Bjg6dbUrA6Z1YMn/6GWx07FB0GnKLhhzAN3mVUJ5/oj+dEaKBC2xTwA4ysjzcTqSSd0JxAEi7pIfQnggTm2hTq1O+xQbhtYQ+fyFgxhjWWBSkDTxKJGtlS0pZ3gWDWDpJDTrNwflrjH7wtHFhuH4eGP7C6pWqil1PqXLU3OMHqjfPJ0feWTjk+zw/H/6El8uk1s1rQjxNgsglbM/dwtd2ns/UGwYvaWo=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then Rscript -e 'covr::coveralls(type =
  "all")' ; fi
