language: r
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
r:
- 3.2
- 3.3
- 3.4
- release
- devel
matrix:
  allow_failures:
  - r: devel
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- export rver=`r_version`; echo $rver ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- jags_install ;
- v8_install ;
- dcmtk_install ;
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- echo "Package Name is $PACKAGE_NAME"
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; then
  shopt -s expand_aliases ; x=`Rscript -e "cat(Sys.which('R'))"` ; echo "reset R"
  ; alias R="travis_wait 100 ${x}" ; fi
- install_python_requirements ;
- R CMD javareconf ;
after_success:
- dump_logs
after_failure:
- dump_logs
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then PKG_TARBALL=$(ls -1t *.tar.gz | head -n
  1); PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'`
  ; mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}"
  ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: 4M0qr/vqQCzcBhVD8oYiCH/pKvhduyK9RaQaHEvo2bq3kmou/n4JYqfRft6SimEC7gEn6YIimnGOuurHeX8Bny6oMnP5z8vky7pYAj9OjYbaimBFOr/uD5G4nUGOTNf4Xforpf4TzanpJ2UOC5hImgGYMrHm5lD+gcNCIvovBZ6xuRXB8eH1TZyJ9HMe8FMLXwZQDMv8KidUM5RW1vOSuHDJLaQgSyWO9Bg1wM4j6AxdlCZGOsTLW7gtV+ewODspqbv1B1u24jYtm8H0sG1r6YBaq8zJqvngRdhcfkjsIEYkCuN1gpj6tgYzds/0csck9uq1zWEBIHdsLWEaGqQ3VMJK/NFcvEOA7xOARfrnPvd6Fxnub3urr2Nn2xzEGZKP6+REh1dwKL9OPSFtgDe4rWzU4Xt2tIt6O5TDGM2ZdKggkJblK19/EkY2R/vIqAm00JLPQOqlIyzSPAOMRmh/n2J8R7eWvS0g4ERvBqfRVRDAvwliMF0mdV+zg4Jw7fGYssD43ETuTTFfSUTgO0lcIRg8QkKJQa50xQl/o3a8fBOjRDeZM3AayLFyyjkQctjISc08Ypa2DhVnUXxFMjKZhX5+y+9mlPbbRFHbNAruG4x8g+WJUELIoE14u+V0gv29gKi5ImisjNJtO0Ba55c08FWTyDcuDouMR298J3pQ5Ys=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" ]];
  then echo 'covr::coveralls(type = "all", quiet = FALSE)' > neuroc_covr.R ; travis_wait
  100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
